services:
  - type: web
    name: gifts-exercise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        sync: false
    healthCheckPath: /docs
